STSShop/STSShop/Areas/Admin/Controllers/SoLuongDkController.cs
using Models.EF;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace STSShop.Areas.Admin.Controllers
{
    public class SoLuongDkController : Controller
    {
        // GET: Admin/TbDaily
        private QLVSDbContext db = new QLVSDbContext();
        public string getMaDL()
        {
            var countRow = db.SoLuongDKs.Count();
            int getCount = countRow + 1;
            string newMaDL = "DK";
            if (getCount < 10) newMaDL += "00" + getCount.ToString();
            else if (getCount < 100) newMaDL += "0" + getCount.ToString();
            return newMaDL;
        }
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;

            var Dailys = (from p in db.SoLuongDKs where p.Flag == true select p);
            Dailys = Dailys.OrderByDescending(s => s.MaDaiLy);

            if (searchString != null)
                page = 1;
            else searchString = currentFilter;
            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                Dailys = Dailys.Where(s => s.MaDaiLy.ToUpper().Contains(searchString.ToUpper()));
                if (Dailys.Count() > 0)
                {
                    TempData["notice"] = "Have result";
                    TempData["dem"] = Dailys.Count();
                }
                else
                {
                    TempData["notice"] = "No result";
                }
            }
            switch (sortOrder)
            {
                case "tendl":
                    Dailys = Dailys.OrderBy(s => s.MaDaiLy);
                    break;
                case "tendl_desc":
                    Dailys = Dailys.OrderByDescending(s => s.MaDaiLy);
                    break;

            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(Dailys.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SoLuongDK sldk = db.SoLuongDKs.Find(id);
            if (sldk == null)
            {
                return HttpNotFound();
            }
            return View(sldk);
        }
        public ActionResult Create()
        {
            SoLuongDK a = new SoLuongDK();
            a.ID = getMaDL();
            ViewBag.MaDaiLy = new SelectList(db.DaiLies, "MaDaiLy", "MaDaiLy");
            return View(a);
        }

        // POST: Admin/TbSanPham/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,MaDaiLy,NgayDK,SoLuongDK1,Flag")] SoLuongDK sldk)
        {
            if (ModelState.IsValid)
            {

                sldk.Flag = true;
                db.SoLuongDKs.Add(sldk);
                TempData["notice"] = "Successfully create";
                TempData["tensanpham"] = sldk.ID;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sldk);
        }
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SoLuongDK sldk = db.SoLuongDKs.Find(id);
            if (sldk == null)
            {
                return HttpNotFound();
            }
            return View(sldk);
        }

        // POST: Admin/TbSanPham/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,MaDaiLy,NgayDK,SoLuongDK1,Flag")] SoLuongDK sldk)
        {
            if (ModelState.IsValid)
            {
                TempData["notice"] = "Successfully edit";
                TempData["tensanpham"] = sldk.ID;
                db.Entry(sldk).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sldk);
        }
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SoLuongDK sldk = db.SoLuongDKs.Find(id);
            if (sldk == null)
            {
                return HttpNotFound();
            }
            return View(sldk);
        }

        // POST: Admin/TbSanPham/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            SoLuongDK dl = db.SoLuongDKs.Find(id);
            dl.Flag = false;
            TempData["notice"] = "Successfully delete";
            TempData["tensanpham"] = dl.ID;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

STSShop/STSShop/Areas/Admin/Views/SoLuongDk/Create.cshtml
@model Models.EF.SoLuongDK
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<h2>Đăng kí số lượng</h2>
@*
    ID varchar(20) primary key,
    MaDaiLy varchar(20),
    NgayDK date,
    SoLuongDK int,
    foreign key (MaDaiLy) references DaiLy(MaDaiLy),
    Flag bit
*@
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sản phẩm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Hidden("size", "155")
        @Html.Hidden("sizedetail", "800")
        <div class="form-group">
            @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @style = "width:50%" } })
                @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MaDaiLy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaDaiLy", null, htmlAttributes: new { @class = "form-control", @style = "width:50%" })
                @Html.ValidationMessageFor(model => model.MaDaiLy, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.NgayDK, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayDK, new { htmlAttributes = new { @class = "form-control", @type = "date", @style = "width:50%" } })
                @Html.ValidationMessageFor(model => model.NgayDK, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongDK1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuongDK1, new { htmlAttributes = new { @class = "form-control", @type = "number", @style = "width:50%" } })
                @Html.ValidationMessageFor(model => model.SoLuongDK1, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <br />
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo mới" class="btn btn-info" />
            </div>
        </div>
    </div>
}
<div>
    <button class="btn btn-default" onclick="location.href='@Url.Action("Index")';return false;"><b>Trở lại</b></button>&nbsp&nbsp&nbsp&nbsp
</div>
<br />

STSShop/STSShop/Areas/Admin/Views/SoLuongDk/Delete.cshtml
@model Models.EF.SoLuongDK
@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<h2>Xóa thông tin</h2>
<h3>Bạn muốn xóa thông tin đăng kí này?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.MaDaiLy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaDaiLy)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.NgayDK)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NgayDK)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.SoLuongDK1)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SoLuongDK1)
        </dd>
        <br />
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-danger" />&nbsp&nbsp&nbsp&nbsp
            <button class="btn btn-default" onclick="location.href='@Url.Action("Index")';return false;"><b>Trở lại</b></button>&nbsp&nbsp&nbsp&nbsp
        </div>
    }
    <br />
    <br />
</div>

STSShop/STSShop/Areas/Admin/Views/SoLuongDk/Details.cshtml
@model Models.EF.SoLuongDK
@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<h2>Chi tiết</h2>
<div>
    <h4>Đại lý</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.MaDaiLy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaDaiLy)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.NgayDK)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NgayDK)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.SoLuongDK1)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SoLuongDK1)
        </dd>
        <br />
        

    </dl>
</div>
<p>
    <button class="btn btn-primary" onclick="location.href='@Url.Action("Edit",  new { id = Model.ID })';return false;"><b> Sửa</b></button>&nbsp&nbsp&nbsp&nbsp
    <button class="btn btn-default" onclick="location.href='@Url.Action("Index")';return false;"><b>Trở lại</b></button>&nbsp&nbsp&nbsp&nbsp
</p>

STSShop/STSShop/Areas/Admin/Views/SoLuongDk/Edit.cshtml
@model Models.EF.SoLuongDK
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<h2>Chỉnh sửa</h2>

@using (Html.BeginForm("Edit", "SoLuongDk", FormMethod.Post, new { @class = "cmxform form-horizontal", @id = "signupForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-horizontal">
        <h4>Sản phẩm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.Flag)

        <div class="form-group">
            @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @style = "width:50%" } })
                @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MaDaiLy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaDaiLy, new { htmlAttributes = new { @class = "form-control", @style = "width:50%" } })
                @Html.ValidationMessageFor(model => model.MaDaiLy, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.NgayDK, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayDK, new { htmlAttributes = new { @class = "form-control", @type = "date", @Value = Model.NgayDK.ToString("yyyy-MM-dd"), @style = "width:50%" } })
                @Html.ValidationMessageFor(model => model.NgayDK, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongDK1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuongDK1, new { htmlAttributes = new { @class = "form-control", @type = "number", @style = "width:50%" } })
                @Html.ValidationMessageFor(model => model.SoLuongDK1, "", new { @class = "text-danger" })
            </div>
        </div>
        

        <br />
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
<div>
    <button class="btn btn-default" onclick="location.href='@Url.Action("Index")';return false;"><b>Trở lại</b></button>&nbsp&nbsp&nbsp&nbsp
</div>
<br />

STSShop/STSShop/Areas/Admin/Views/SoLuongDk/Index.cshtml
@model PagedList.IPagedList<Models.EF.SoLuongDK>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<br />
<h2>Số lượng đăng kí</h2>
<br />
@using (Html.BeginForm("Index", "SoLuongDk", FormMethod.Get))
{
    <p>
        Nhập tên đại lý: @Html.TextBox("searchString", ViewBag.CurrentFilter as string)
        <button type="submit"><i class="fa fa-search"></i></button>
    </p>
    <br />
}
@if (TempData["notice"] != null)
{
    if (TempData["notice"].ToString() == "Successfully create")
    {
        <div class="alert alert-success" role="alert">
            <strong>Thông báo! </strong>Đăng kí số lượng vé thành công !!
        </div>
    }
    else
    if (TempData["notice"].ToString() == "Successfully edit")
    {
        <div class="alert alert-success" role="alert">
            <strong>Thông báo! </strong>Thay đổi thông tin số lượng thành công
        </div>
    }
    else
    if (TempData["notice"].ToString() == "Successfully delete")
    {
        <div class="alert alert-success" role="alert">
            <strong>Thông báo! </strong>Đã xóa thành công
        </div>
    }
    else if (TempData["notice"].ToString() == "Have result")
    {
        <div class="alert alert-info" role="alert">
            <strong>Tìm kiếm thành công! </strong>
        </div>
    }
    else if (TempData["notice"].ToString() == "No result")
    {
        <div class="alert alert-danger" role="alert">
            <strong> Không có kết quả trả về!</strong>
        </div>
    }
}
<p>
    <button class="btn btn-info" onclick="location.href='@Url.Action("Create")';return false;">Tạo mới</button>&nbsp;&nbsp;&nbsp;&nbsp;
    <button class="btn btn-warning" onclick="location.href='@Url.Action("Index")';return false;">Tải lại</button>
</p>
<table class="table table-striped table-bordered table-hover" id="dataTables-example">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Mã đại lý
            </th>
            <th>
                Ngày đăng ký
            </th>
            <th>
                Số lượng đăng ký
            </th>
            
            <th>
                <p style="text-align:center">Chức năng</p>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaDaiLy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgayDK)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SoLuongDK1)
                </td>
                

                <td align="center">
                    <button class="btn btn-success" onclick="location.href='@Url.Action("Details",  new { id = item.ID })';return false;">Xem</button>&nbsp&nbsp&nbsp&nbsp
                    <button class="btn btn-primary" onclick="location.href='@Url.Action("Edit",  new { id = item.ID })';return false;">Sửa</button>&nbsp&nbsp&nbsp&nbsp
                    <button class="btn btn-danger" onclick="location.href='@Url.Action("Delete",  new { id = item.ID })';return false;">Xóa</button>&nbsp&nbsp&nbsp&nbsp
                </td>
            </tr>
        }
    </tbody>
</table>
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) của
@Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index",
new
{
    page,
    sortOrder = ViewBag.CurrentSort,
    currentFilter = ViewBag.CurrentFilter
}))