STSShop/STSShop/Areas/Admin/Controllers/PhieuChisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Models.EF;
using PagedList;

namespace STSShop.Areas.Admin.Controllers
{
    public class PhieuChisController : Controller
    {
        private QLVSDbContext db = new QLVSDbContext();

        // GET: Admin/PhieuChis
        public ActionResult Index(string currentFilter, string searchString, int? page)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            var phieu = db.PhieuChis.ToList();
            if (!String.IsNullOrEmpty(searchString))
            {
                phieu = phieu.Where(s => s.MaPhieuChi.ToUpper().Contains(searchString.ToUpper())).ToList();
            }

            phieu.OrderByDescending(v => v.MaPhieuChi);
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View(phieu.ToPagedList(pageNumber, pageSize));
        }

        // GET: Admin/PhieuChis/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhieuChi phieuChi = db.PhieuChis.Find(id);
            if (phieuChi == null)
            {
                return HttpNotFound();
            }
            return View(phieuChi);
        }
        public string getMaDL()
        {
            var countRow = db.PhieuChis.Count();
            int getCount = countRow + 1;
            string newMaDL = "PCH";
            if (getCount < 10) newMaDL += "000" + getCount.ToString();
            else if (getCount < 100) newMaDL += "00" + getCount.ToString();
            return newMaDL;
        }
        // GET: Admin/PhieuChis/Create
        public ActionResult Create()
        {
            PhieuChi a = new PhieuChi();
            a.MaPhieuChi = getMaDL();
            return View(a);
        }

        // POST: Admin/PhieuChis/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaPhieuChi,Ngay,NoiDung,SoTien")] PhieuChi phieuChi)
        {
            if (ModelState.IsValid)
            {

                
                db.PhieuChis.Add(phieuChi);
                TempData["notice"] = "Successfully create";
                TempData["tensanpham"] = phieuChi.MaPhieuChi;
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            return View(phieuChi);
        }

        // GET: Admin/PhieuChis/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhieuChi phieuChi = db.PhieuChis.Find(id);
            if (phieuChi == null)
            {
                return HttpNotFound();
            }
            return View(phieuChi);
        }

        // POST: Admin/PhieuChis/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaPhieuChi,Ngay,NoiDung,SoTien")] PhieuChi phieuChi)
        {
            if (ModelState.IsValid)
            {
                DbContextTransaction tran = db.Database.BeginTransaction();
                try
                {
                    TempData["notice"] = "Successfully edit";
                    TempData["ma"] = phieuChi.MaPhieuChi;
                    db.Entry(phieuChi).State = EntityState.Modified;
                    db.SaveChanges();
                    tran.Commit();
                    tran.Dispose();
                }
                catch
                {
                    tran.Rollback();
                    tran.Dispose();

                }
                return RedirectToAction("Index");
            }
            return View(phieuChi);
        }

        // GET: Admin/PhieuChis/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhieuChi phieuChi = db.PhieuChis.Find(id);
            if (phieuChi == null)
            {
                return HttpNotFound();
            }
            return View(phieuChi);
        }

        // POST: Admin/PhieuChis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            PhieuChi pc = db.PhieuChis.Find(id);
            db.PhieuChis.Remove(pc);
            TempData["notice"] = "Successfully delete";
            TempData["tensanpham"] = pc.MaPhieuChi;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

STSShop/STSShop/Areas/Admin/Views/PhieuChis/Create.cshtml
@model Models.EF.PhieuChi

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Tạo Mới</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Phiếu Chi</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.MaPhieuChi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaPhieuChi, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.MaPhieuChi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ngay, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ngay, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
            @Html.ValidationMessageFor(model => model.Ngay, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NoiDung, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SoTien, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SoTien, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoTien, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Tạo mới" class="btn btn-info" />
        </div>
    </div>
</div>
}

<div>
    <button class="btn btn-default" onclick="location.href='@Url.Action("Index")';return false;"><b>Trở lại</b></button>&nbsp&nbsp&nbsp&nbsp
</div>

STSShop/STSShop/Areas/Admin/Views/PhieuChis/Delete.cshtml
@model Models.EF.PhieuChi

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Xóa Thông Tin</h2>

<h3>Bạn muốn xóa thông tin phiếu chi</h3>
<div>
    <h4>Phiếu Chi</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ngay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngay)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.NoiDung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoiDung)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.SoTien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoTien)
        </dd>
        <br />
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-danger" /> &nbsp&nbsp&nbsp&nbsp
            <button class="btn btn-default" onclick="location.href='@Url.Action("Index")';return false;"><b>Trở lại</b></button>&nbsp&nbsp&nbsp&nbsp
        </div>
    }
</div>

STSShop/STSShop/Areas/Admin/Views/PhieuChis/Details.cshtml
@model Models.EF.PhieuChi

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Xem Thông Tin</h2>

<div>
    <h4>Phiếu Chi</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaPhieuChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaPhieuChi)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.Ngay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngay)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.NoiDung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoiDung)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.SoTien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoTien)
        </dd>
        <br />
    </dl>
</div>
<p>
    <button class="btn btn-primary" onclick="location.href='@Url.Action("Edit",  new { id = Model.MaPhieuChi })';return false;"><b> Sửa</b></button>&nbsp&nbsp&nbsp&nbsp
    <button class="btn btn-default" onclick="location.href='@Url.Action("Index")';return false;"><b>Trở lại</b></button>&nbsp&nbsp&nbsp&nbsp
</p>

STSShop/STSShop/Areas/Admin/Views/PhieuChis/Edit.cshtml
@model Models.EF.PhieuChi

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Sữa Thông Tin</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Phiếu Chi</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaPhieuChi)

        <div class="form-group">
            @Html.LabelFor(model => model.MaPhieuChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaPhieuChi, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.MaPhieuChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ngay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ngay, new { htmlAttributes = new { @class = "form-control", @type = "date", @Value = Model.Ngay.ToString("yyyy-MM-dd") } })
                @Html.ValidationMessageFor(model => model.Ngay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoiDung, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoTien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoTien, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
                @Html.ValidationMessageFor(model => model.SoTien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <button class="btn btn-default" onclick="location.href='@Url.Action("Index")';return false;"><b>Trở lại</b></button>&nbsp&nbsp&nbsp&nbsp
</div>

STSShop/STSShop/Areas/Admin/Views/PhieuChis/Index.cshtml
@model PagedList.IPagedList<Models.EF.PhieuChi>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<br />
<h2>Phiếu chi</h2>
<br />
@using (Html.BeginForm("Index", "PhieuChis", FormMethod.Get))
{
    <p>
        Nhập tên mã phiếu chi: @Html.TextBox("searchString", ViewBag.CurrentFilter as string)
        <button type="submit"><i class="fa fa-search"></i></button>
    </p>
    <br />
}
@if (TempData["notice"] != null)
{
    if (TempData["notice"].ToString() == "Successfully create")
    {
        <div class="alert alert-success" role="alert">
            <strong>Thông báo! </strong>Thêm phiếu chi thành công !!
        </div>
    }
    else
    if (TempData["notice"].ToString() == "Successfully edit")
    {
        <div class="alert alert-success" role="alert">
            <strong>Thông báo! </strong>Thay đổi phiếu chi thành công !!
        </div>
    }
    else
    if (TempData["notice"].ToString() == "Successfully delete")
    {
        <div class="alert alert-success" role="alert">
            <strong>Thông báo! </strong>Đã xóa thành công
        </div>
    }
    else if (TempData["notice"].ToString() == "Have result")
    {
        <div class="alert alert-info" role="alert">
            <strong>Tìm kiếm thành công! </strong>
        </div>
    }
    else if (TempData["notice"].ToString() == "No result")
    {
        <div class="alert alert-danger" role="alert">
            <strong> Không có kết quả trả về!</strong>
        </div>
    }
}
<p>
    <button class="btn btn-info" onclick="location.href='@Url.Action("Create")';return false;">Tạo mới</button>&nbsp;&nbsp;&nbsp;&nbsp;
    <button class="btn btn-warning" onclick="location.href='@Url.Action("Index")';return false;">Tải lại</button>
</p>
<table class="table table-striped table-bordered table-hover" id="dataTables-example">
    <thead>
        <tr>
            <th>
                Mã phiếu chi
            </th>
            <th>
                Ngày
            </th>
            <th>
                Nội dung
            </th>
            <th>
                Số tiền
            </th>
            <th>
                <p style="text-align:center">Chức năng</p>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MaPhieuChi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ngay)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NoiDung)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SoTien)
                </td>
                
                <td align="center">
                    <button class="btn btn-success" onclick="location.href='@Url.Action("Details",  new { id = item.MaPhieuChi})';return false;">Xem</button>&nbsp&nbsp&nbsp&nbsp
                    <button class="btn btn-primary" onclick="location.href='@Url.Action("Edit",  new { id = item.MaPhieuChi})';return false;">Sửa</button>&nbsp&nbsp&nbsp&nbsp
                    <button class="btn btn-danger" onclick="location.href='@Url.Action("Delete", new { id = item.MaPhieuChi})';return false;">Xóa</button>&nbsp&nbsp&nbsp&nbsp
                </td>
            </tr>
        }
    </tbody>
</table>
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) của
@Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index",
new
{
    page,
    sortOrder = ViewBag.CurrentSort,
    currentFilter =
ViewBag.CurrentFilter
}))