STSShop/STSShop/Areas/Admin/Controllers/GiaisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Models.EF;
using PagedList;

namespace STSShop.Areas.Admin.Controllers
{
    public class GiaisController : Controller
    {
        private QLVSDbContext db = new QLVSDbContext();
        //cus



        // GET: Admin/Giais
        public ActionResult Index(string currentFilter, string searchString, int? page)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            var giai = (from p in db.Giais where p.Flag == true select p).ToList();
           
            if (!String.IsNullOrEmpty(searchString))
            {
                giai = giai.Where(s => s.TenGiai.ToUpper().Contains(searchString.ToUpper())).ToList();
            }

            giai.OrderByDescending(v => v.MaGiai);
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View(giai.ToPagedList(pageNumber, pageSize));
        }

        // GET: Admin/Giais/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Giai giai = db.Giais.Find(id);
            if (giai == null)
            {
                return HttpNotFound();
            }
            return View(giai);
        }

        // GET: Admin/Giais/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Giais/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaGiai,TenGiai,SoTienNhan,Flag")] Giai giai)
        {
            if (ModelState.IsValid)
            {
                var tran = db.Database.BeginTransaction();
                try
                {
                    TempData["notice"] = "Successfully create";
                    TempData["tengiai"] = giai.TenGiai;
                    db.Giais.Add(giai);
                    db.SaveChanges();
                    tran.Commit();
                    tran.Dispose();
                }
                catch
                {
                    tran.Rollback();
                    tran.Dispose();
                }
                return RedirectToAction("Index");
            }

            return View(giai);
        }

        // GET: Admin/Giais/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Giai giai = db.Giais.Find(id);
            if (giai == null)
            {
                return HttpNotFound();
            }
            return View(giai);
        }

        // POST: Admin/Giais/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaGiai,TenGiai,SoTienNhan,Flag")] Giai giai)
        {
            if (ModelState.IsValid)
            {
                DbContextTransaction tran = db.Database.BeginTransaction();
                try
                {
                    giai.Flag = true;
                    TempData["notice"] = "Successfully edit";
                    TempData["tengiai"] = giai.TenGiai;
                    db.Entry(giai).State = EntityState.Modified;
                    db.SaveChanges();
                    tran.Commit();
                    tran.Dispose();
                }
                catch
                {
                    tran.Rollback();
                    tran.Dispose();

                }
                return RedirectToAction("Index");
            }
            return View(giai);
        }

        // GET: Admin/Giais/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Giai giai = db.Giais.Find(id);
            if (giai == null)
            {
                return HttpNotFound();
            }
            return View(giai);
        }

        // POST: Admin/Giais/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {

            DbContextTransaction tran = db.Database.BeginTransaction();
            try
            {
                var giai = db.Giais.Find(id);
                TempData["notice"] = "Successfully delete";
                TempData["tengiai"] = giai.TenGiai;
                giai.Flag = false;
                db.SaveChanges();
                tran.Commit();
                tran.Dispose();
            }
            catch
            {
                tran.Rollback();
                tran.Dispose();
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

STSShop/STSShop/Areas/Admin/Views/Giais/Create.cshtml
@model Models.EF.Giai

@{
    ViewBag.Title = "Tạo Giải";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Tạo mới Giải</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Quản lý Giải</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaGiai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaGiai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaGiai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenGiai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenGiai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenGiai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoTienNhan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoTienNhan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoTienNhan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Flag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Flag)
                    @Html.ValidationMessageFor(model => model.Flag, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    <button class="btn btn-default" onclick="location.href='@Url.Action("Index")';return false;"><b>Trở lại</b></button>&nbsp&nbsp&nbsp&nbsp
</div>

STSShop/STSShop/Areas/Admin/Views/Giais/Delete.cshtml
@model Models.EF.Giai

@{
    ViewBag.Title = "Xóa";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Xóa thông tin </h2>

<h3>Bạn muốn xóa thông tin Giải <em>@Html.DisplayFor(model => model.TenGiai)</em> này?</h3>
<div>
    <h4>Giai</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenGiai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenGiai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoTienNhan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoTienNhan)
        </dd>

        

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-danger" /> &nbsp&nbsp&nbsp&nbsp
            <button class="btn btn-default" onclick="location.href='@Url.Action("Index")';return false;"><b>Trở lại</b></button>&nbsp&nbsp&nbsp&nbsp
        </div>
    }
</div>

STSShop/STSShop/Areas/Admin/Views/Giais/Details.cshtml
@model Models.EF.Giai

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Thông tin chi tiết</h2>

<div>
    <h4>Giải <em>@Html.DisplayFor(model => model.TenGiai)</em> </h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenGiai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenGiai)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.SoTienNhan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoTienNhan)
        </dd>
        <br />


    </dl>
</div>
<p>
    <button class="btn btn-primary" onclick="location.href='@Url.Action("Edit",  new { id = Model.MaGiai })';return false;"><b> Sửa</b></button>&nbsp&nbsp&nbsp&nbsp
    <button class="btn btn-default" onclick="location.href='@Url.Action("Index")';return false;"><b>Trở lại</b></button>&nbsp&nbsp&nbsp&nbsp
</p>

STSShop/STSShop/Areas/Admin/Views/Giais/Edit.cshtml
@model Models.EF.Giai

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Chỉnh sửa</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Giải @Html.DisplayFor(model => model.MaGiai)</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaGiai)

        <div class="form-group">
            @Html.LabelFor(model => model.TenGiai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenGiai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenGiai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoTienNhan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoTienNhan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoTienNhan, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <button class="btn btn-default" onclick="location.href='@Url.Action("Index")';return false;"><b>Trở lại</b></button>&nbsp&nbsp&nbsp&nbsp
</div>

STSShop/STSShop/Areas/Admin/Views/Giais/Index.cshtml
@model PagedList.IPagedList<Models.EF.Giai>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>QUẢN LÝ GIẢI XỔ SỐ</h2>
<hr />
@using (Html.BeginForm("Index", "Giais", FormMethod.Get))
{
    <p>
        Nhập tên giải: @Html.TextBox("searchString", ViewBag.CurrentFilter as string)
        <button type="submit"><i class="fa fa-search"></i></button>
    </p>
    <br />
}

@if (TempData["notice"] != null)
{
    if (TempData["notice"].ToString() == "Successfully create")
    {
        <div class="alert alert-success" role="alert">
            <strong>Thông báo! </strong>Thêm thông tin Giải: @TempData["tengiai"] thành công
        </div>
    }
    else
    if (TempData["notice"].ToString() == "Successfully edit")
    {
        <div class="alert alert-success" role="alert">
            <strong>Thông báo! </strong>Sửa thông tin Giải: @TempData["tengiai"] thành công
        </div>
    }
    else
    if (TempData["notice"].ToString() == "Successfully delete")
    {
        <div class="alert alert-success" role="alert">
            <strong>Thông báo! </strong>Xóa thông tin Giải: @TempData["tengiai"] thành công
        </div>
    }
    else if (TempData["notice"].ToString() == "Have result")
    {
        <div class="alert alert-info" role="alert">
            <strong>Tìm kiếm thành công! </strong>Có @TempData["dem"] kết quả trả về!
        </div>
    }
    else if (TempData["notice"].ToString() == "No result")
    {
        <div class="alert alert-danger" role="alert">
            <strong> Không có kết quả trả về!</strong>
        </div>
    }
}

<p>
    <button class="btn btn-info" onclick="location.href='@Url.Action("Create")';return false;">Tạo mới</button>&nbsp;&nbsp;&nbsp;&nbsp;
    <button class="btn btn-warning" onclick="location.href='@Url.Action("Index")';return false;">Tải lại</button>
</p>
<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>
            Tên Giải
        </th>
        <th>
            Số tiền nhận
        </th>
        <th>
            <p >Chức năng</p>
        </th>
        
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenGiai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoTienNhan)
            </td>
            
            <td>
                <button class="btn btn-success" onclick="location.href='@Url.Action("Details",  new { id = item.MaGiai })';return false;">Xem</button>&nbsp&nbsp&nbsp&nbsp
                <button class="btn btn-primary" onclick="location.href='@Url.Action("Edit",  new { id = item.MaGiai })';return false;">Sửa</button>&nbsp&nbsp&nbsp&nbsp
                <button class="btn btn-danger" onclick="location.href='@Url.Action("Delete",  new { id = item.MaGiai })';return false;">Xóa</button>&nbsp&nbsp&nbsp&nbsp
            </td>
        </tr>
    }

</table>
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) của @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index",
new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))