STSShop/STSShop/Areas/Admin/Controllers/TbDailyController.cs
using Models.EF;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace STSShop.Areas.Admin.Controllers
{
    public class TbDailyController : Controller
    {
        // GET: Admin/TbDaily
        private QLVSDbContext db = new QLVSDbContext();
        public string getMaDL()
        {
            var countRow = db.DaiLies.Count();
            int getCount = countRow + 1;
            string newMaDL = "DL";
            if (getCount < 10) newMaDL += "0" + getCount.ToString();
            else if (getCount < 100) newMaDL += "0" + getCount.ToString();
            return newMaDL;
        }
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            


            var Dailys = (from p in db.DaiLies where p.Flag==true select p);
            Dailys = Dailys.OrderByDescending(s => s.MaDaiLy);

            if (searchString != null)
                page = 1;
            else searchString = currentFilter;
            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                Dailys = Dailys.Where(s => s.TenDaiLy.ToUpper().Contains(searchString.ToUpper()));
                if (Dailys.Count() > 0)
                {
                    TempData["notice"] = "Have result";
                    TempData["dem"] = Dailys.Count();
                }
                else
                {
                    TempData["notice"] = "No result";
                }
            }
            switch (sortOrder)
            {
                case "tendl":
                    Dailys = Dailys.OrderBy(s => s.TenDaiLy);
                    break;
                case "tendl_desc":
                    Dailys = Dailys.OrderByDescending(s => s.TenDaiLy);
                    break;
                
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(Dailys.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DaiLy dly = db.DaiLies.Find(id);
            if (dly == null)
            {
                return HttpNotFound();
            }
            return View(dly);
        }
        public ActionResult Create()
        {
            DaiLy dl = new DaiLy();
            dl.MaDaiLy = getMaDL();
            
            return View(dl);
        }


        
        // POST: Admin/TbSanPham/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDaiLy,TenDaiLy,DiaChi,SDT,Flag")] DaiLy dl)
        {
            

            if (ModelState.IsValid)
            {
                
                dl.Flag =true;
                db.DaiLies.Add(dl);
                TempData["notice"] = "Successfully create";
                TempData["tensanpham"] = dl.TenDaiLy;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            
            return View(dl);
        }
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DaiLy dl = db.DaiLies.Find(id);
            if (dl == null)
            {
                return HttpNotFound();
            }
            
            return View(dl);
        }

        // POST: Admin/TbSanPham/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDaiLy,TenDaiLy,DiaChi,SDT,Flag")] DaiLy dl)
        {
            

            if (ModelState.IsValid)
            {
                TempData["notice"] = "Successfully edit";
                TempData["tensanpham"] = dl.TenDaiLy;
                db.Entry(dl).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            return View(dl);
        }
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DaiLy dl = db.DaiLies.Find(id);
            if (dl == null)
            {
                return HttpNotFound();
            }
            return View(dl);
        }

        // POST: Admin/TbSanPham/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            DaiLy dl = db.DaiLies.Find(id);
            dl.Flag = false;
            TempData["notice"] = "Successfully delete";
            TempData["tensanpham"] = dl.TenDaiLy;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

STSShop/STSShop/Areas/Admin/Views/TbDaily/Create.cshtml
@model Models.EF.DaiLy

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Tạo mới</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sản phẩm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Hidden("size", "155")
        @Html.Hidden("sizedetail", "800")
        <div class="form-group">
            @Html.LabelFor(model => model.MaDaiLy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaDaiLy, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @style = "width:50%" } })
                @Html.ValidationMessageFor(model => model.MaDaiLy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenDaiLy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenDaiLy, new { htmlAttributes = new { @class = "form-control", @style = "width:50%" } })
                @Html.ValidationMessageFor(model => model.TenDaiLy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control", @style = "width:50%" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control", @type = "number",@style = "width:50%" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <br />
        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo mới" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    <button class="btn btn-default" onclick="location.href='@Url.Action("Index")';return false;"><b>Trở lại</b></button>&nbsp&nbsp&nbsp&nbsp
</div>
<br />

STSShop/STSShop/Areas/Admin/Views/TbDaily/Delete.cshtml
@model Models.EF.DaiLy

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Xóa thông tin</h2>

<h3>Bạn muốn xóa thông tin đại lý này?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">

        

        <dt>
            @Html.DisplayNameFor(model => model.MaDaiLy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaDaiLy)
        </dd>

        <br />

        <dt>
            @Html.DisplayNameFor(model => model.TenDaiLy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenDaiLy)
        </dd>

        <br />

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <br />

        <dt>
            @Html.DisplayNameFor(model => model.SDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>

        <br />

        



    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-danger" />&nbsp&nbsp&nbsp&nbsp
            <button class="btn btn-default" onclick="location.href='@Url.Action("Index")';return false;"><b>Trở lại</b></button>&nbsp&nbsp&nbsp&nbsp
        </div>
    }
    <br />
    <br />
</div>

STSShop/STSShop/Areas/Admin/Views/TbDaily/Details.cshtml
@model Models.EF.DaiLy

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<h2>Chi tiết</h2>

<div>
    <h4>Đại lý</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaDaiLy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaDaiLy)
        </dd>

        <br />

        <dt>
            @Html.DisplayNameFor(model => model.TenDaiLy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenDaiLy)
        </dd>

        <br />

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <br />

        <dt>
            @Html.DisplayNameFor(model => model.SDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>

        <br />

        

    </dl>
</div>
<p>
    <button class="btn btn-primary" onclick="location.href='@Url.Action("Edit",  new { id = Model.MaDaiLy })';return false;"><b> Sửa</b></button>&nbsp&nbsp&nbsp&nbsp
    <button class="btn btn-default" onclick="location.href='@Url.Action("Index")';return false;"><b>Trở lại</b></button>&nbsp&nbsp&nbsp&nbsp
</p>

STSShop/STSShop/Areas/Admin/Views/TbDaily/Edit.cshtml
@model Models.EF.DaiLy

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Chỉnh sửa</h2>


@using (Html.BeginForm("Edit", "TbDaily", FormMethod.Post, new { @class = "cmxform form-horizontal", @id = "signupForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-horizontal">
        <h4>Sản phẩm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaDaiLy)
        @Html.HiddenFor(model => model.Flag)
        

        <div class="form-group">
            @Html.LabelFor(model => model.MaDaiLy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaDaiLy, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @style = "width:50%" } })
                @Html.ValidationMessageFor(model => model.MaDaiLy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenDaiLy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenDaiLy, new { htmlAttributes = new { @class = "form-control", @style = "width:50%" } })
                @Html.ValidationMessageFor(model => model.TenDaiLy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control", @style = "width:50%" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control",@style = "width:50%" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <br />
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    <button class="btn btn-default" onclick="location.href='@Url.Action("Index")';return false;"><b>Trở lại</b></button>&nbsp&nbsp&nbsp&nbsp
</div>
<br />

STSShop/STSShop/Areas/Admin/Views/TbDaily/Index.cshtml
@model PagedList.IPagedList<Models.EF.DaiLy>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<br />
<h2>Quản lí đại lý</h2>
<br />
@using (Html.BeginForm("Index", "TbDaily", FormMethod.Get))
{
    <p>
        Nhập tên đại lý: @Html.TextBox("searchString", ViewBag.CurrentFilter as string)
        <button type="submit"><i class="fa fa-search"></i></button>
    </p>
    <br />
}

@if (TempData["notice"] != null)
{
    if (TempData["notice"].ToString() == "Successfully create")
    {
        <div class="alert alert-success" role="alert">
            <strong>Thông báo! </strong>Thêm thông tin đại lý: @TempData["tensanpham"] thành công
        </div>
    }
    else
    if (TempData["notice"].ToString() == "Successfully edit")
    {
        <div class="alert alert-success" role="alert">
            <strong>Thông báo! </strong>Sửa thông tin đại lý: @TempData["tensanpham"] thành công
        </div>
    }
    else
    if (TempData["notice"].ToString() == "Successfully delete")
    {
        <div class="alert alert-success" role="alert">
            <strong>Thông báo! </strong>Xóa thông tin đại lý: @TempData["tensanpham"] thành công
        </div>
    }
    else if (TempData["notice"].ToString() == "Have result")
    {
        <div class="alert alert-info" role="alert">
            <strong>Tìm kiếm thành công! </strong>Có @TempData["dem"] kết quả trả về!
        </div>
    }
    else if (TempData["notice"].ToString() == "No result")
    {
        <div class="alert alert-danger" role="alert">
            <strong> Không có kết quả trả về!</strong>
        </div>
    }
}

<p>
    <button class="btn btn-info" onclick="location.href='@Url.Action("Create")';return false;">Tạo mới</button>&nbsp;&nbsp;&nbsp;&nbsp;
    <button class="btn btn-warning" onclick="location.href='@Url.Action("Index")';return false;">Tải lại</button>
</p>

<table class="table table-striped table-bordered table-hover" id="dataTables-example">
    <thead>
        <tr>
            <th>
                Mã đại lý
            </th>
            <th width="17%">
                Tên đại lý
            </th>
            <th width="40%">
                Địa chỉ
            </th>
            <th width="9%">
                SĐT
            </th>
            <th>
                <p style="text-align:center">Chức năng</p>
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MaDaiLy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TenDaiLy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DiaChi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SDT)
                </td>
                
                <td align="center">
                    <button class="btn btn-success" onclick="location.href='@Url.Action("Details",  new { id = item.MaDaiLy })';return false;">Xem</button>&nbsp&nbsp&nbsp&nbsp
                    <button class="btn btn-primary" onclick="location.href='@Url.Action("Edit",  new { id = item.MaDaiLy })';return false;">Sửa</button>&nbsp&nbsp&nbsp&nbsp
                    <button class="btn btn-danger" onclick="location.href='@Url.Action("Delete",  new { id = item.MaDaiLy })';return false;">Xóa</button>&nbsp&nbsp&nbsp&nbsp
                </td>
            </tr>
        }
    </tbody>
</table>
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) của
@Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index",
new
{
    page,
    sortOrder = ViewBag.CurrentSort,
    currentFilter =
ViewBag.CurrentFilter
}))